export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
              "inverse-surface": "#dae2fd",
              "primary": "#a5d0b9",
              "on-secondary-fixed-variant": "#574500",
              "surface-dim": "#0b1326",
              "surface-tint": "#a5d0b9",
              "on-primary": "#0e3727",
              "on-tertiary-container": "#75b393",
              "on-error": "#690005",
              "secondary-fixed": "#ffe088",
              "on-tertiary-fixed-variant": "#0e5138",
              "outline-variant": "#414844",
              "surface-bright": "#31394d",
              "inverse-primary": "#3f6653",
              "on-tertiary": "#003824",
              "tertiary-fixed": "#b1f0ce",
              "tertiary": "#95d4b3",
              "primary-fixed-dim": "#a5d0b9",
              "inverse-on-surface": "#283044",
              "secondary-container": "#af8d11",
              "on-primary-fixed": "#002114",
              "outline": "#8b938d",
              "background": "#0b1326",
              "surface-container-low": "#131b2e",
              "surface-container": "#171f33",
              "on-secondary-container": "#342800",
              "on-surface": "#dae2fd",
              "tertiary-container": "#00452e",
              "secondary-fixed-dim": "#e9c349",
              "on-primary-container": "#86af99",
              "error-container": "#93000a",
              "surface-container-highest": "#2d3449",
              "on-surface-variant": "#c1c8c2",
              "tertiary-fixed-dim": "#95d4b3",
              "secondary": "#e9c349",
              "on-error-container": "#ffdad6",
              "error": "#ffb4ab",
              "on-secondary": "#3c2f00",
              "surface-container-high": "#222a3d",
              "on-tertiary-fixed": "#002114",
              "surface": "#0b1326",
              "surface-container-lowest": "#060e20",
              "surface-variant": "#2d3449",
              "on-primary-fixed-variant": "#274e3d",
              "on-background": "#dae2fd",
              "primary-fixed": "#c1ecd4",
              "on-secondary-fixed": "#241a00",
              "primary-container": "#1b4332",
              "brand": {
                "green": '#1B4332',
                "gold": '#D4AF37',
                "light": '#F8F9FA',
                "dark": '#0F172A',
              }
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
